version: 2

sources:
  - name: cdc_staging  
    description: "Rohe CDC Events, die vom Prefect Flow aus MinIO in DuckDB geladen wurden."

    schema: main 

    tables:
      - name: aisles  
        identifier: stg_raw_aisles 

      - name: departments
        identifier: stg_raw_departments

      - name: products
        identifier: stg_raw_products

      - name: users
        identifier: stg_raw_users

      - name: orders
        identifier: stg_raw_orders

      - name: order_products 
        identifier: stg_raw_order_products 