name: 'dbt_setup'
version: '1.0.0'
config-version: 2

profile: 'dbt_setup'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_setup:
    +database: default
    +materialized: view 

    staging:
      +schema: staging 

    intermediate:
      +materialized: table
      +schema: intermediate

    marts:
      +materialized: incremental
      +schema: marts 

snapshots:
  dbt_setup:
    +database: default
    +target_schema: default_marts


seeds:
  dbt_setup:
    +database: default
    +schema: raw_seeds 

    stg_raw_aisles:
      +enabled: true
      +delimiter: ','
      +strict: false 

    stg_raw_products:
      +enabled: true
      +delimiter: ','
      +strict: false

    stg_raw_users:
      +enabled: true
      +delimiter: ','
      +strict: false

    stg_raw_departments:
      +enabled: true
      +delimiter: ','
      +strict: false