
name: 'dbt_setup'
version: '1.0.0'

profile: 'dbt_setup'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

seeds:
  dbt_setup: 
    stg_raw_aisles:
      +enabled: true
      +config:
        delimiter: ','   
        strict_mode: false
    stg_raw_products:
      +enabled: true
      +config:
        delimiter: ','   
        strict_mode: false
    stg_raw_users: 
      +enabled: true
      +config:
        delimiter: ','   
        strict_mode: false
    stg_raw_departments: 
      +enabled: true
      +config:
        delimiter: ','   
        strict_mode: false      


