# models/staging/schema.yml
# ACHTUNG: Diese Datei ersetzt Ihre fälschlicherweise hier platzierte sources.yml.
# Sie dient zur Beschreibung und zum Testen Ihrer Staging-MODELLE.

version: 2

models:
  - name: stg_aisles
    description: "Bereinigte CDC-Events für Aisles (Gänge). Enthält den letzten bekannten Stand pro Ladezyklus für jeden Aisle."
    columns:
      - name: aisle_id
        description: "Eindeutiger Primärschlüssel für den Gang."
        tests:
          - unique
          - not_null
      - name: aisle
        description: "Name des Gangs."
      - name: op_type
        description: "Operationstyp aus den CDC-Daten (c=create, u=update, d=delete)."
        tests:
          - accepted_values:
              values: ['c', 'u', 'd', 'r'] # 'r' für Snapshot-Read
      - name: source_timestamp_ms
        description: "Zeitstempel des ursprünglichen CDC-Events in Millisekunden."
      - name: staging_load_timestamp
        description: "Zeitstempel, wann der Datensatz in die DuckDB Staging-Tabelle geladen wurde."

  - name: stg_departments
    description: "Bereinigte CDC-Events für Departments (Abteilungen)."
    columns:
      - name: department_id
        description: "Eindeutiger Primärschlüssel für die Abteilung."
        tests:
          - unique
          - not_null
      - name: department
        description: "Name der Abteilung."
      - name: op_type
        description: "Operationstyp aus den CDC-Daten (c, u, d, r)."
        tests:
          - accepted_values:
              values: ['c', 'u', 'd', 'r']
      - name: source_timestamp_ms
        description: "Zeitstempel des ursprünglichen CDC-Events in Millisekunden."
      - name: staging_load_timestamp
        description: "Zeitstempel, wann der Datensatz in die DuckDB Staging-Tabelle geladen wurde."

  - name: stg_products
    description: "Bereinigte CDC-Events für Products (Produkte)."
    columns:
      - name: product_id
        description: "Eindeutiger Primärschlüssel für das Produkt."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name des Produkts."
      - name: aisle_id
        description: "Fremdschlüssel zum Gang (aisle)."
        # Optional: Beziehungstest zu stg_aisles (nachdem Marts gebaut sind, eher dort testen)
        # tests:
        #   - relationships:
        #       to: ref('stg_aisles') # Oder dim_aisles, falls erstellt
        #       field: aisle_id
      - name: department_id
        description: "Fremdschlüssel zur Abteilung (department)."
      - name: op_type
        description: "Operationstyp aus den CDC-Daten (c, u, d, r)."
        tests:
          - accepted_values:
              values: ['c', 'u', 'd', 'r']
      - name: source_timestamp_ms
        description: "Zeitstempel des ursprünglichen CDC-Events in Millisekunden."
      - name: staging_load_timestamp
        description: "Zeitstempel, wann der Datensatz in die DuckDB Staging-Tabelle geladen wurde."

  - name: stg_users
    description: "Bereinigte CDC-Events für Users (Benutzer)."
    columns:
      - name: user_id
        description: "Eindeutiger Primärschlüssel für den Benutzer."
        tests:
          - unique
          - not_null
      - name: op_type
        description: "Operationstyp aus den CDC-Daten (c, u, d, r)."
        tests:
          - accepted_values:
              values: ['c', 'u', 'd', 'r']
      - name: source_timestamp_ms
        description: "Zeitstempel des ursprünglichen CDC-Events in Millisekunden."
      - name: staging_load_timestamp
        description: "Zeitstempel, wann der Datensatz in die DuckDB Staging-Tabelle geladen wurde."

  - name: stg_orders
    description: "Bereinigte CDC-Events für Orders (Bestellungen)."
    columns:
      - name: order_id
        description: "Eindeutiger Primärschlüssel für die Bestellung."
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Fremdschlüssel zum Benutzer."
        tests:
          - not_null
          # Optional: Beziehungstest
          # - relationships:
          #     to: ref('stg_users') # Oder dim_users
          #     field: user_id
      - name: order_timestamp
        description: "Zeitstempel der Bestellung."
        tests:
          - not_null
      - name: tip_given
        description: "Gibt an, ob Trinkgeld gegeben wurde (TRUE/FALSE)."
      - name: op_type
        description: "Operationstyp aus den CDC-Daten (c, u, d, r)."
        tests:
          - accepted_values:
              values: ['c', 'u', 'd', 'r']
      - name: source_timestamp_ms
        description: "Zeitstempel des ursprünglichen CDC-Events in Millisekunden."
      - name: staging_load_timestamp
        description: "Zeitstempel, wann der Datensatz in die DuckDB Staging-Tabelle geladen wurde."

  - name: stg_order_products
    description: "Bereinigte CDC-Events für Order_Products (Bestellpositionen)."
    columns:
      - name: order_id
        description: "Fremdschlüssel zur Bestellung."
        tests:
          - not_null
      - name: product_id
        description: "Fremdschlüssel zum Produkt."
        tests:
          - not_null
      - name: add_to_cart_order
        description: "Reihenfolge, in der das Produkt zum Warenkorb hinzugefügt wurde."
      - name: op_type
        description: "Operationstyp aus den CDC-Daten (c, u, d, r)."
        tests:
          - accepted_values:
              values: ['c', 'u', 'd', 'r']
      - name: source_timestamp_ms
        description: "Zeitstempel des ursprünglichen CDC-Events in Millisekunden."
      - name: staging_load_timestamp
        description: "Zeitstempel, wann der Datensatz in die DuckDB Staging-Tabelle geladen wurde."
    # Test für zusammengesetzten Schlüssel (Beispiel)
    tests:
       - dbt_utils.unique_combination_of_columns:
           combination_of_columns:
             - order_id
             - product_id

  # Optional: Wenn Sie das stg_order_tips Modell erstellt haben
  # - name: stg_order_tips
  #   description: "Extrahiert Tip-Informationen aus Order-Events."
  #   columns:
  #     - name: order_id
  #       tests:
  #         - not_null
  #         # Unique hier eventuell nicht sinnvoll, wenn Orders geupdated werden können
  #     - name: tip_given
  #     - name: op_type
  #     - name: source_timestamp_ms
  #     - name: staging_load_timestamp