[project]
name = "consumers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka~=2.4.0",
    "minio>=7.2.15",
    "pandas>=2.2.3",
    "prefect>=3.3.7",
    "pyarrow>=20.0.0",
]


